training:
  # Indicies split
  split:
    val_size: 0.25
    random_state: 42

  # Data augmentations
  transforms:
    random_rotation: 10
    random_translate: [0.05, 0.05]
    random_scale: [0.95, 1.05]

  datamodule:
    name: "image_only"
    kwargs:
      batch_size: 32
      num_workers: 0
      train_val_images_path: "${globals:precomputed_root}/${globals:resize}/train_images.npy"
      test_images_path: "${globals:precomputed_root}/${globals:resize}/test_images.npy"
      y_train_val_path: "${globals:precomputed_root}/${globals:resize}/train_labels.npy"
      y_test_path: "${globals:precomputed_root}/${globals:resize}/test_labels.npy"

  classifier:
    name: "cxr_classifier"
    kwargs:
      num_classes: 14
      transition_dim: 2048
      pooling: "lse"
      lse_r: 10.0
      backbone_trainable_layers:
        - "layer4"


  # ligthning wrapper for the classifier
  lit_module:
    name: "default_classifier"
    kwargs:
      num_classes: 14
      lr: 0.0001
      threshold: 0.5

  trainer:
    max_epochs: 40
    precision: "16-mixed"
    log_every_n_steps: 10
    accumulate_grad_batches: 1
    patience: 5
    mlflow_experiment_name: "${globals:mlflow_experiment_name}"
    run_name: "${globals:run_name}"
